### ISSUE TITLE
Unresposive files and launch issues

### ISSUE THREAD

**Issue by PoyBoi** [PoyBoi/StableDiffusionHelper#5]
hi, i am attempting to install and run your package, but i do not see a "run.bat" to launch after installation.

i followed the steps which instructed me to download "install.bat" and run, which completed successfully.

there are three batch files created in the stablediffusionhelper subfolder (gui.bat, ipynb.bat, and troubleshoot.bat) however after running each of them the files complete downloading/updating and then exit.

_Originally posted by @ride5k in https://github.com/PoyBoi/StableDiffusionHelper/discussions/3#discussioncomment-11238939_

**Comment by imago10** [comment]
> hi, i am attempting to install and run your package, but i do not see a "run.bat" to launch after installation.
> 
> i followed the steps which instructed me to download "install.bat" and run, which completed successfully.
> 
> there are three batch files created in the stablediffusionhelper subfolder (gui.bat, ipynb.bat, and troubleshoot.bat) however after running each of them the files complete downloading/updating and then exit.
> 
> _Originally posted by @ride5k in [#3 (comment)](https://github.com/PoyBoi/StableDiffusionHelper/discussions/3#discussioncomment-11238939)_

Same here, please let me know if you find a solution.

**Comment by PoyBoi** [comment]
> > hi, i am attempting to install and run your package, but i do not see a "run.bat" to launch after installation.
> > i followed the steps which instructed me to download "install.bat" and run, which completed successfully.
> > there are three batch files created in the stablediffusionhelper subfolder (gui.bat, ipynb.bat, and troubleshoot.bat) however after running each of them the files complete downloading/updating and then exit.
> > _Originally posted by @ride5k in [#3 (comment)](https://github.com/PoyBoi/StableDiffusionHelper/discussions/3#discussioncomment-11238939)_
> 
> Same here, please let me know if you find a solution.

@imago10, have you tried running the `gui.bat` or 'ipynb.bat' file ? If neither of them work, can you try running 'troubleshoot.bat' and letting me know if it fixes the issue ?

**Comment by imago10** [comment]
Hi,

Yes I tried that but it didn't work. It just quit after I’m press 0 or run
any other bat file.

Regards
Lukasz

**Comment by PoyBoi** [comment]
@imago10 
> Hi,
> Yes I tried that but it didn't work. It just quit after I’m press 0 or run any other bat file.
>...

Have you instead tried to reinstall remBG by pressing 1 ? Please do let me know if that helps, if not I think there might be a more underlying issue.

Apart from that, I believe you're using a GPU (hopefully NVIDIA GPU) on your setup ?

**Comment by PoyBoi** [comment]
CLOS
